# ComfyUI Configuration
# Unified configuration for models and custom nodes
#
# This is a minimal default config for fast setup.
# For advanced setups (WAN Animate, SDXL, etc.), see config.example.yml

# ============================================================================
# Models Configuration
# ============================================================================
models:
  # SD 1.5 Model (Basic image generation)
  - url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors
    destination: checkpoints
    optional: false

  # You can add more models here or use config.example.yml as a reference
  # For WAN Animate 2.2, SDXL, or other advanced models, see config.example.yml

# ============================================================================
# Custom Nodes Configuration
# ============================================================================
nodes:
  # ComfyUI Manager - Essential package manager for installing other nodes via UI
  - url: https://github.com/ltdrdata/ComfyUI-Manager.git
    version: latest

  # Use ComfyUI Manager UI to install additional nodes, or add them here
  # For advanced node setups (WAN Animate, etc.), see config.example.yml

# ============================================================================
# Valid Model Destinations
# ============================================================================
# checkpoints, clip, clip_vision, configs, controlnet, diffusion_models,
# embeddings, loras, upscale_models, vae, sams, detection, text_encoders,
# unet, style_models, hypernetworks

# ============================================================================
# Valid Node Version Specifiers
# ============================================================================
# latest    - Latest stable release (git tag)
# nightly   - Latest commit on default branch
# v1.2.3    - Specific version tag (semver)
# abc123    - Specific commit hash
# main      - Specific branch name
