services:
  # ComfyUI + Handler with auto-install/update
  # ComfyUI is auto-cloned to ./ComfyUI on first run (updateable, persistent)
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: artokun/comfyui-runpod:latest
    container_name: comfyui
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - RUN_MODE=development  # Use 'development' for local, 'production' for RunPod
      - COMFYUI_PATH=/workspace/ComfyUI
      - AUTO_UPDATE=${AUTO_UPDATE:-false}  # Set to 'true' for auto-updates on startup
    ports:
      - "8188:8188"  # ComfyUI web interface
      - "8000:8000"  # RunPod API handler
      - "8888:8888"  # Jupyter Lab
    volumes:
      # Single workspace directory (contains everything: ComfyUI, outputs, workflows, models)
      - ./workspace:/workspace
      # Configuration file (edit without rebuilding!)
      - ./config.yml:/workspace/config.yml
      # Examples directory (test scripts and workflows)
      - ./examples:/app/examples
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
