name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-title-check:
    name: PR Title Check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

  file-changes:
    name: Check File Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List changed files
        run: |
          echo "Changed files:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done

      - name: Check for sensitive files
        run: |
          SENSITIVE_FILES=".env|credentials|secrets|keys"
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -E "$SENSITIVE_FILES"; then
            echo "::warning::Sensitive files detected in PR. Please review carefully."
          fi

  size-check:
    name: PR Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check PR size
        uses: marketplace/actions/pull-request-size@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          max_size: 500
          ignore_pattern: |
            *.lock
            *.md
            tests/**

  auto-label:
    name: Auto Label PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
