name: Publish Docker Images

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (e.g., v1.0.0)'
        required: true

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ada, blackwell]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/comfyui-runpod
          tags: |
            type=semver,pattern={{version}},suffix=-${{ matrix.arch }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.arch }}
            type=raw,value=${{ matrix.arch }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: production
          build-args: |
            GPU_ARCH=${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  create-manifest:
    name: Create Multi-Arch Manifest
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push manifest
        run: |
          TAG=${{ github.event.release.tag_name || github.event.inputs.tag }}
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/comfyui-runpod:${TAG} \
            --amend ${{ secrets.DOCKER_USERNAME }}/comfyui-runpod:${TAG}-ada \
            --amend ${{ secrets.DOCKER_USERNAME }}/comfyui-runpod:${TAG}-blackwell
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/comfyui-runpod:${TAG}
